# Generated by Django 5.2.7 on 2025-10-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tone', models.TextField(verbose_name='口調')),
                ('prediction', models.TextField(verbose_name='予想')),
                ('index', models.CharField(default='', max_length=50, verbose_name='指数')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField(verbose_name='内容')),
            ],
        ),
    ]
