# Generated by Django 5.2.7 on 2025-11-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_mediaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='key_name',
            field=models.CharField(default='temp_key', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
