# Generated by Django 5.2.7 on 2025-11-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_mediaitem_key_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
